### ISSUE TITLE
New proverbs

### ISSUE THREAD

**Issue by intoinside** [intoinside/ItalianProverbsBadlyTranslated#8]
- [x] If my grandmother had wheels, she would be a barrow
- [x] If my grandfather had three balls, he would be a flipper
- [x] In four and four eight
- [x] You are climbing on mirrors
- [x] We have made thirty, let's make thirtyone
- [x] There's no two without three, and four come naturally
- [x] Where there is taste there is no loss - Dove c'è gusto non c'è perdenza
- [x] Raisins and does not say goodbye - L'uva passa e non saluta
- [x] Don't poop outside the potty - Non cagare fuori dal vasino

**Comment by raffaeleintorcia** [comment]
You like to play with the fire - Ti piace giocare con il fuoco
An ugly female cat to peel off - Una brutta gatta da pelare
